// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkPn1mXsJ0h32uwdImbv5gR9XpD9sgQWE',
    appId: '1:927668152816:web:73205cba757f9553acd535',
    messagingSenderId: '927668152816',
    projectId: 'votos-3420a',
    authDomain: 'votos-3420a.firebaseapp.com',
    databaseURL: 'https://votos-3420a-default-rtdb.firebaseio.com',
    storageBucket: 'votos-3420a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSyjidw1cmZRaQQCp07WaY63Pjaetdtno',
    appId: '1:927668152816:android:80b38e4c249a2737acd535',
    messagingSenderId: '927668152816',
    projectId: 'votos-3420a',
    databaseURL: 'https://votos-3420a-default-rtdb.firebaseio.com',
    storageBucket: 'votos-3420a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeB9zQgJ41ED8xveo9L0PiFGXXz1F3sOk',
    appId: '1:927668152816:ios:b0edf446a080ae98acd535',
    messagingSenderId: '927668152816',
    projectId: 'votos-3420a',
    databaseURL: 'https://votos-3420a-default-rtdb.firebaseio.com',
    storageBucket: 'votos-3420a.firebasestorage.app',
    iosClientId:
        '927668152816-dpamk5updrpms0hltel8nuf378qqsqku.apps.googleusercontent.com',
    iosBundleId: 'com.votomusicamundial.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeB9zQgJ41ED8xveo9L0PiFGXXz1F3sOk',
    appId: '1:927668152816:ios:b0edf446a080ae98acd535',
    messagingSenderId: '927668152816',
    projectId: 'votos-3420a',
    databaseURL: 'https://votos-3420a-default-rtdb.firebaseio.com',
    storageBucket: 'votos-3420a.firebasestorage.app',
    iosClientId:
        '927668152816-dpamk5updrpms0hltel8nuf378qqsqku.apps.googleusercontent.com',
    iosBundleId: 'com.votomusicamundial.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkPn1mXsJ0h32uwdImbv5gR9XpD9sgQWE',
    appId: '1:927668152816:web:276b36d7e0ce51e5acd535',
    messagingSenderId: '927668152816',
    projectId: 'votos-3420a',
    authDomain: 'votos-3420a.firebaseapp.com',
    databaseURL: 'https://votos-3420a-default-rtdb.firebaseio.com',
    storageBucket: 'votos-3420a.firebasestorage.app',
  );
}
